waypoints:
  # waypoints should be named wp_0, wp_1, wp_2....
  # all waypoints need to have a label (even if it's empty), frame_id, and a coordinate pair coords
  # the state machine will run these IN ORDER, so make sure they're numbered IN_ORDER
  #   (only the number matters, their actual order in this file doesn't)
  # there's no upper limit on the number of waypoints, but if there aren't ANY, the AUTO state won't do anything.

  wp_0: 
    label: "start"
    frame_id: map
    coords: [0.0, 0.0]
  wp_1: 
    label: ""
    frame_id: map
    coords: [1.0, 0.0]
  wp_2: 
    label: ""
    frame_id: map
    coords: [2.0, 0.0]
  wp_3: 
    label: "end"
    frame_id: map
    coords: [3.0, 0.0]